cache:
  directories:
  - $HOME/.isabelle
  - $HOME/.opam
sudo: required
before_install:
- sudo apt-get -qq update
- sudo apt-get -qq install libgmp3-dev
- wget https://isabelle.in.tum.de/dist/Isabelle2016-1_app.tar.gz
- tar xf Isabelle2016-1_app.tar.gz
- export PATH=./Isabelle2016-1/bin:$PATH
script:
- travis_wait 30 isabelle build -o quick_and_dirty -j 2 -d . all
